package com.example.kartonki.ui.theme

import androidx.compose.runtime.compositionLocalOf
import com.example.kartonki.domain.model.Rarity

// ─── Data class ──────────────────────────────────────────────────────────────

data class AppStrings(
    // Rarity names
    val rarityCommon: String,
    val rarityUncommon: String,
    val rarityRare: String,
    val rarityEpic: String,
    val rarityLegendary: String,
    // Rarity short names (for filter chips)
    val rarityCommonShort: String,
    val rarityUncommonShort: String,
    val rarityRareShort: String,
    val rarityEpicShort: String,
    val rarityLegendaryShort: String,
    val filterAll: String,

    // Home
    val homeSubtitle: String,
    val homePveButton: String,
    val homePvpButton: String,
    val homeCollectionButton: String,
    val homeShopButton: String,
    val homeProblemWordsTitle: (Int) -> String,
    val homeProblemWordsSubtitle: String,
    val homePackReady: String,

    // Study
    val studyTitle: String,
    val studyBack: String,

    // Study session
    val studyNewWord: String,
    val studyGotIt: String,
    val studyQTranslation: String,
    val studyQDefinition: String,
    val studyQDefinitionNative: String,
    val studyQWordFromDef: String,
    val studyQWordFromDefNative: String,
    val studyQFillBlank: String,
    val studyQFillBlankNative: String,
    val studyContinue: String,
    val studyIncorrect: String,
    val studySessionComplete: String,
    val studyCorrectLabel: String,
    val studyIncorrectLabel: String,
    val studyNewSession: String,
    val studyBackHome: String,
    val studyNoWords: String,

    // Word set detail
    val setDetailStartButton: String,
    val setDetailProgress: (Int, Int) -> String,

    // Problem words session
    val problemWordsTitle: String,
    val problemWordsEmpty: String,
    val problemWordsBack: String,
    val problemWordsCompleteTitle: String,
    val problemWordsCorrectLabel: String,
    val problemWordsIncorrectLabel: String,
    val problemWordsImproved: (Int, Int) -> String,
    val problemWordsNoImprovement: String,
    val problemWordsRetry: String,

    // Collection
    val collectionTitle: String,
    val collectionCount: (Int) -> String,
    val collectionBuildDeck: String,
    val collectionEmpty: String,

    // Deck builder
    val deckBuilderTitle: String,
    val deckBuilderSize: (Int, Int) -> String,
    val deckTabInDeck: (Int) -> String,
    val deckTabAvailable: (Int) -> String,
    val deckEmptyDeck: String,
    val deckEmptyAvailable: String,

    // My decks
    val myDecksTitle: String,
    val myDecksCollectionLink: String,
    val myDecksCreate: String,
    val myDecksEmpty: String,
    val myDecksEdit: String,
    val myDecksDelete: String,
    val myDecksCreateDialogTitle: String,
    val myDecksCreateDialogHint: String,
    val myDecksCreateDialogLevel: String,
    val myDecksCreateDialogConfirm: String,
    val myDecksCreateDialogCancel: String,
    val myDecksDeleteTitle: String,
    val myDecksDeleteConfirm: (String) -> String,
    val deckCardCount: (Int, Int) -> String,
    val deckInvalidLabel: String,
    val deckInvalidHint: String,

    // PvP
    val pvpDeckSelectTitle: String,
    val pvpNoDecks: String,
    val pvpPlayer1Label: String,
    val pvpPlayer2Label: String,
    val pvpNameHint: String,
    val pvpDeckHint: String,
    val pvpStartGame: String,
    val pvpLevelMismatch: String,
    val pvpDeckInvalidWarning: String,
    val pvpDeckCardCount: (Int) -> String,
    val pvpSurrender: String,
    val pvpContinue: String,
    val pvpPlayAgain: String,
    val pvpGoHome: String,
    val pvpSurrenderDialogTitle: String,
    val pvpCancel: String,
    val pvpGotIt: String,
    val pvpTurn: (String) -> String,
    val pvpSelectCard: String,
    val pvpInDeck: (Int) -> String,
    val pvpTaskFor: (String) -> String,
    val pvpGameEnded: String,
    val pvpGameOver: String,
    val pvpForfeit: (String) -> String,
    val pvpAfk: (String) -> String,
    val pvpScore: (Int) -> String,
    val pvpWinner: (String) -> String,
    val pvpDraw: String,
    val pvpSurrenderConfirm: (String) -> String,

    // Pack shop
    val shopTitle: String,
    val shopPackNameFor: (String) -> String,
    val shopPackCards: String,
    val shopOpenButton: String,
    val shopOpenMultiple: (Int) -> String,
    val shopNoPacks: String,
    val shopEarnPacks: String,
    val shopCountLabel: String,
    val shopHavePacks: (Int) -> String,

    // Pack opening
    val packOpeningLoading: String,
    val packOpeningTitle: String,
    val packOpeningProgress: (Int, Int) -> String,
    val packOpeningRevealAll: String,
    val packOpeningToShop: String,
    val packOpeningToHome: String,

    // New cards
    val newCardsTitle: String,
    val newCardsSubtitle: String,
    val newCardsCollect: String,

    // Player stats
    val statsPlayerTitle: String,
    val statsProgressSection: String,
    val statsWordsLearned: String,
    val statsAccuracy: String,
    val statsSeriesSection: String,
    val statsCurrentStreakLabel: String,
    val statsRecordLabel: String,
    val statsStreakDays: (Int) -> String,
    val statsPvpSection: String,
    val statsPvpWins: String,
    val statsPvpLosses: String,
    val statsPvpDraws: String,
    val statsBestPvpScore: String,

    // Word stats
    val wordStatsTitle: String,
    val wordStatsSortDifficult: String,
    val wordStatsSortEasiest: String,
    val wordStatsSortFrequent: String,
    val wordStatsSortRecent: String,
    val wordStatsEmpty: String,
    val wordStatsProblemTitle: (Int) -> String,
    val wordStatsProblemSubtitle: String,
    val wordStatsErrors: (Int) -> String,
    val wordStatsEncounters: (Int) -> String,

    // Achievements
    val achievementsTitle: String,
    val achievementsProgress: (Int, Int) -> String,
    val achievementsRemaining: (Int) -> String,
    val achievementsAllDone: String,
    val achievementsReward: String,

    // Settings
    val settingsTitle: String,
    val settingsProfileSection: String,
    val settingsAvatarLabel: String,
    val settingsFromGallery: String,
    val settingsPlayerName: String,
    val settingsCancelButton: String,
    val settingsAppearanceSection: String,
    val settingsDarkTheme: String,
    val settingsLanguageSection: String,
    val settingsTasksSection: String,
    val settingsStudyLanguage: String,
    val settingsDefinitionMode: String,
    val settingsFillBlankMode: String,
    val settingsQuizTypesLabel: String,
    val settingsQuizTypesCount: (Int, Int) -> String,
    val settingsDone: String,
    val settingsProblemWordsSource: String,
    val settingsProblemWordsSourceTitle: String,
    val settingsNativeLanguage: String,
    val settingsChooseNativeLanguage: String,
    val settingsStudyLanguageTitle: String,
    val settingsProgressSection: String,
    val settingsPlayerStats: String,
    val settingsWordStats: String,
    val settingsAchievements: String,

    // Quiz mode labels (used in settings pickers)
    val quizModeLabels: Map<String, String>,

    // Quiz type labels (used in settings pickers)
    val quizTypeLabels: Map<String, String>,

    // Problem words source labels (used in settings pickers)
    val problemWordsSourceLabels: Map<String, String>,
)

// ─── Extension ───────────────────────────────────────────────────────────────

fun Rarity.localizedName(s: AppStrings): String = when (this) {
    Rarity.COMMON    -> s.rarityCommon
    Rarity.UNCOMMON  -> s.rarityUncommon
    Rarity.RARE      -> s.rarityRare
    Rarity.EPIC      -> s.rarityEpic
    Rarity.LEGENDARY -> s.rarityLegendary
}

fun Rarity.localizedShortName(s: AppStrings): String = when (this) {
    Rarity.COMMON    -> s.rarityCommonShort
    Rarity.UNCOMMON  -> s.rarityUncommonShort
    Rarity.RARE      -> s.rarityRareShort
    Rarity.EPIC      -> s.rarityEpicShort
    Rarity.LEGENDARY -> s.rarityLegendaryShort
}

// ─── CompositionLocal ────────────────────────────────────────────────────────

val LocalAppStrings = compositionLocalOf<AppStrings> { RuStrings }

// ─── Language instances ───────────────────────────────────────────────────────

val RuStrings = AppStrings(
    rarityCommon    = "Обычный",
    rarityUncommon  = "Необычный",
    rarityRare      = "Редкий",
    rarityEpic      = "Эпический",
    rarityLegendary = "Легендарный",
    rarityCommonShort    = "Обыч",
    rarityUncommonShort  = "Необыч",
    rarityRareShort      = "Редк",
    rarityEpicShort      = "Эпич",
    rarityLegendaryShort = "Легенд",
    filterAll       = "Все",

    homeSubtitle           = "Изучай слова, собирай карточки",
    homePveButton          = "Изучать слова",
    homePvpButton          = "Сыграть матч (PvP)",
    homeCollectionButton   = "Коллекция карточек",
    homeShopButton         = "🛒  Магазин паков",
    homeProblemWordsTitle  = { n -> "Проблемные слова: $n" },
    homeProblemWordsSubtitle = "Поработать над ошибками?",
    homePackReady          = "Пак готов!",

    studyTitle = "Изучать слова",
    studyBack  = "← Назад",

    studyNewWord           = "Новое слово",
    studyGotIt             = "Понятно!",
    studyQTranslation      = "Выберите перевод:",
    studyQDefinition       = "Выберите определение:",
    studyQDefinitionNative = "Выберите определение:",
    studyQWordFromDef      = "Выберите слово по определению:",
    studyQWordFromDefNative= "Выберите слово по описанию:",
    studyQFillBlank        = "Выберите слово для пропуска:",
    studyQFillBlankNative  = "Выберите слово для пропуска:",
    studyContinue          = "Продолжить",
    studyIncorrect         = "Неправильно",
    studySessionComplete   = "Сессия завершена!",
    studyCorrectLabel      = "Правильно",
    studyIncorrectLabel    = "Ошибок",
    studyNewSession        = "Новая сессия",
    studyBackHome          = "На главную",
    studyNoWords           = "Нет слов для изучения.",

    setDetailStartButton = "Заниматься",
    setDetailProgress    = { done, total -> "Изучено: $done / $total слов" },

    problemWordsTitle        = "Проблемные слова",
    problemWordsEmpty        = "Нет проблемных слов!\nПродолжай в том же духе.",
    problemWordsBack         = "Назад",
    problemWordsCompleteTitle= "Работа над ошибками завершена!",
    problemWordsCorrectLabel = "Верно",
    problemWordsIncorrectLabel = "Ошибок",
    problemWordsImproved     = { imp, total -> "Улучшено: $imp из $total слов" },
    problemWordsNoImprovement= "Слова пока не улучшились — продолжай!",
    problemWordsRetry        = "Ещё раз",

    collectionTitle     = "Коллекция",
    collectionCount     = { n -> "$n карт" },
    collectionBuildDeck = "Строить колоду",
    collectionEmpty     = "Коллекция пуста",

    deckBuilderTitle    = "Конструктор колоды",
    deckBuilderSize     = { cur, max -> "$cur / $max карт" },
    deckTabInDeck       = { n -> "В колоде ($n)" },
    deckTabAvailable    = { n -> "Доступно ($n)" },
    deckEmptyDeck       = "Колода пуста — добавьте карты",
    deckEmptyAvailable  = "Все карты уже в колоде",

    myDecksTitle              = "Мои колоды",
    myDecksCollectionLink     = "Коллекция",
    myDecksCreate             = "Создать колоду",
    myDecksEmpty              = "Нет колод — создайте первую!",
    myDecksEdit               = "Редактировать",
    myDecksDelete             = "Удалить",
    myDecksCreateDialogTitle  = "Новая колода",
    myDecksCreateDialogHint   = "Название колоды",
    myDecksCreateDialogLevel  = "Уровень колоды:",
    myDecksCreateDialogConfirm= "Создать",
    myDecksCreateDialogCancel = "Отмена",
     myDecksDeleteTitle        = "Удалить колоду?",
     myDecksDeleteConfirm      = { name -> "Удалить «$name»? Это действие нельзя отменить." },
    deckCardCount             = { cur, max -> "$cur / $max карт" },
    deckInvalidLabel          = "Состав не соответствует уровню",
    deckInvalidHint           = "Откройте колоду и исправьте состав карт",

    pvpDeckSelectTitle  = "PvP — Выбор колод",
    pvpNoDecks          = "Создайте хотя бы одну колоду перед игрой",
    pvpPlayer1Label     = "Игрок 1",
    pvpPlayer2Label     = "Игрок 2",
    pvpNameHint         = "Имя игрока",
    pvpDeckHint         = "Выберите колоду",
    pvpStartGame        = "Начать игру",
    pvpLevelMismatch    = "Выберите колоды одинакового уровня",
    pvpDeckInvalidWarning = "Одна или обе колоды не соответствуют своему уровню",
    pvpDeckCardCount    = { n -> "$n карт" },
    pvpSurrender        = "Сдаться",
    pvpContinue         = "Продолжить",
    pvpPlayAgain        = "Играть снова",
    pvpGoHome           = "На главную",
    pvpSurrenderDialogTitle = "Сдаться?",
    pvpCancel           = "Отмена",
    pvpGotIt            = "Понял!",
    pvpTurn             = { name -> "Ход: $name" },
    pvpSelectCard       = "Выберите карту для атаки",
    pvpInDeck           = { n -> "В колоде: $n" },
    pvpTaskFor          = { name -> "Задание для $name" },
    pvpGameEnded        = "Игра завершена",
    pvpGameOver         = "Игра окончена!",
    pvpForfeit          = { name -> "$name сдался(-ась)." },
    pvpAfk              = { name -> "$name выбыл(-а) за неактивность." },
    pvpScore            = { n -> "$n очков" },
    pvpWinner           = { name -> "Победитель: $name 🎉" },
    pvpDraw             = "Ничья!",
    pvpSurrenderConfirm = { name -> "$name, вы уверены, что хотите сдаться?\nПротивнику будет засчитана победа." },

    shopTitle       = "Магазин Паков",
    shopPackNameFor = { pair -> if (pair == "he-ru") "Иврит пак" else "Английский пак" },
    shopPackCards   = "5 карточек за пак",
    shopOpenButton  = "Открыть",
    shopOpenMultiple= { n -> "Открыть  ($n пака)" },
    shopNoPacks     = "Нет паков",
    shopEarnPacks   = "Играй PvE или PvP чтобы получить бесплатный пак",
    shopCountLabel  = "Количество",
    shopHavePacks   = { n -> "Доступно: $n" },

    packOpeningLoading  = "Открываем пак...",
    packOpeningTitle    = "✦  Открытие пака  ✦",
    packOpeningProgress = { rev, total -> "$rev/$total открыто" },
    packOpeningRevealAll= "Открыть все",
    packOpeningToShop   = "В магазин",
    packOpeningToHome   = "На главную",

    newCardsTitle    = "🎴 Новые карточки!",
    newCardsSubtitle = "Слова изучены — карточки получены!",
    newCardsCollect  = "Забрать всё",

    statsPlayerTitle     = "Статистика игрока",
    statsProgressSection = "Прогресс",
    statsWordsLearned    = "Слов изучено",
    statsAccuracy        = "Точность ответов",
    statsSeriesSection   = "Серия",
    statsCurrentStreakLabel = "Текущая",
    statsRecordLabel     = "Рекорд",
    statsStreakDays       = { n -> "$n дн." },
    statsPvpSection      = "PvP-режим",
    statsPvpWins         = "Победы",
    statsPvpLosses       = "Поражения",
    statsPvpDraws        = "Ничьи",
    statsBestPvpScore    = "Лучший счёт",

    wordStatsTitle          = "Статистика слов",
    wordStatsSortDifficult  = "Сложные",
    wordStatsSortEasiest    = "Лёгкие",
    wordStatsSortFrequent   = "Частые",
    wordStatsSortRecent     = "Недавние",
    wordStatsEmpty          = "Ещё нет данных.\nНачни занятия!",
    wordStatsProblemTitle   = { n -> "Проблемные слова: $n" },
    wordStatsProblemSubtitle= "Нажми, чтобы начать работу над ошибками",
    wordStatsErrors         = { pct -> "$pct% ошибок" },
    wordStatsEncounters     = { n -> "$n раз" },

    achievementsTitle    = "Достижения",
    achievementsProgress = { got, total -> "Получено: $got / $total" },
    achievementsRemaining= { n -> "$n осталось" },
    achievementsAllDone  = "Все получены! 🎉",
    achievementsReward   = "🏆 Награда",

    settingsTitle                  = "Настройки",
    settingsProfileSection         = "Профиль",
    settingsAvatarLabel            = "Аватар",
    settingsFromGallery            = "Из галереи",
    settingsPlayerName             = "Имя игрока",
    settingsCancelButton           = "Отмена",
    settingsAppearanceSection      = "Оформление",
    settingsDarkTheme              = "Тёмная тема",
    settingsLanguageSection        = "Языки",
    settingsTasksSection           = "Задания",
    settingsStudyLanguage          = "Язык изучения",
    settingsDefinitionMode         = "Задания с определением",
    settingsFillBlankMode          = "Задания со вставкой слова",
    settingsQuizTypesLabel         = "Типы заданий (PvE)",
    settingsQuizTypesCount         = { n, total -> "$n из $total" },
    settingsDone                   = "Готово",
    settingsProblemWordsSource     = "Проблемные слова учитывать из",
    settingsProblemWordsSourceTitle= "Учитывать ошибки из",
    settingsNativeLanguage         = "Родной язык",
    settingsChooseNativeLanguage   = "Выберите родной язык",
    settingsStudyLanguageTitle     = "Язык изучения",
    settingsProgressSection        = "Прогресс",
    settingsPlayerStats            = "📊  Статистика игрока",
    settingsWordStats              = "📖  Статистика по словам",
    settingsAchievements           = "🏆  Достижения",

    quizModeLabels = linkedMapOf(
        "foreign" to "На изучаемом языке",
        "native"  to "На родном языке",
        "both"    to "Оба варианта",
    ),
    quizTypeLabels = linkedMapOf(
        "translation" to "Перевод (4 варианта)",
        "definition"  to "Определение",
        "fill_blank"  to "Вставка слова",
    ),
    problemWordsSourceLabels = linkedMapOf(
        "both"     to "PvE + PvP вместе",
        "pve_only" to "Только PvE",
        "pvp_only" to "Только PvP",
    ),
)

val EnStrings = AppStrings(
    rarityCommon    = "Common",
    rarityUncommon  = "Uncommon",
    rarityRare      = "Rare",
    rarityEpic      = "Epic",
    rarityLegendary = "Legendary",
    rarityCommonShort    = "Comm",
    rarityUncommonShort  = "Uncomm",
    rarityRareShort      = "Rare",
    rarityEpicShort      = "Epic",
    rarityLegendaryShort = "Legend",
    filterAll       = "All",

    homeSubtitle           = "Learn words, collect cards",
    homePveButton          = "Study words",
    homePvpButton          = "Play match (PvP)",
    homeCollectionButton   = "Card collection",
    homeShopButton         = "🛒  Card shop",
    homeProblemWordsTitle  = { n -> "Problem words: $n" },
    homeProblemWordsSubtitle = "Work on your mistakes?",
    homePackReady          = "Pack ready!",

    studyTitle = "Study words",
    studyBack  = "← Back",

    studyNewWord           = "New word",
    studyGotIt             = "Got it!",
    studyQTranslation      = "Choose the translation:",
    studyQDefinition       = "Choose the definition:",
    studyQDefinitionNative = "Choose the definition:",
    studyQWordFromDef      = "Choose the word by definition:",
    studyQWordFromDefNative= "Choose the word by description:",
    studyQFillBlank        = "Choose the word for the gap:",
    studyQFillBlankNative  = "Choose the word for the gap:",
    studyContinue          = "Continue",
    studyIncorrect         = "Incorrect",
    studySessionComplete   = "Session complete!",
    studyCorrectLabel      = "Correct",
    studyIncorrectLabel    = "Mistakes",
    studyNewSession        = "New session",
    studyBackHome          = "Home",
    studyNoWords           = "No words to study.",

    setDetailStartButton = "Start studying",
    setDetailProgress    = { done, total -> "Studied: $done / $total words" },

    problemWordsTitle        = "Problem words",
    problemWordsEmpty        = "No problem words!\nKeep it up.",
    problemWordsBack         = "Back",
    problemWordsCompleteTitle= "Review session complete!",
    problemWordsCorrectLabel = "Correct",
    problemWordsIncorrectLabel = "Mistakes",
    problemWordsImproved     = { imp, total -> "Improved: $imp of $total words" },
    problemWordsNoImprovement= "No improvement yet — keep going!",
    problemWordsRetry        = "Try again",

    collectionTitle     = "Collection",
    collectionCount     = { n -> "$n cards" },
    collectionBuildDeck = "Build deck",
    collectionEmpty     = "Collection is empty",

    deckBuilderTitle    = "Deck builder",
    deckBuilderSize     = { cur, max -> "$cur / $max cards" },
    deckTabInDeck       = { n -> "In deck ($n)" },
    deckTabAvailable    = { n -> "Available ($n)" },
    deckEmptyDeck       = "Deck is empty — add cards",
    deckEmptyAvailable  = "All cards are already in the deck",

    myDecksTitle              = "My decks",
    myDecksCollectionLink     = "Collection",
    myDecksCreate             = "Create deck",
    myDecksEmpty              = "No decks — create the first one!",
    myDecksEdit               = "Edit",
    myDecksDelete             = "Delete",
    myDecksCreateDialogTitle  = "New deck",
    myDecksCreateDialogHint   = "Deck name",
    myDecksCreateDialogLevel  = "Deck level:",
    myDecksCreateDialogConfirm= "Create",
    myDecksCreateDialogCancel = "Cancel",
     myDecksDeleteTitle        = "Delete deck?",
     myDecksDeleteConfirm      = { name -> "Delete \"$name\"? This action cannot be undone." },
    deckCardCount             = { cur, max -> "$cur / $max cards" },
    deckInvalidLabel          = "Composition doesn't match level",
    deckInvalidHint           = "Open the deck and fix the card composition",

    pvpDeckSelectTitle  = "PvP — Select decks",
    pvpNoDecks          = "Create at least one deck before playing",
    pvpPlayer1Label     = "Player 1",
    pvpPlayer2Label     = "Player 2",
    pvpNameHint         = "Player name",
    pvpDeckHint         = "Select deck",
    pvpStartGame        = "Start game",
    pvpLevelMismatch    = "Select decks of the same level",
    pvpDeckInvalidWarning = "One or both decks don't match their level",
    pvpDeckCardCount    = { n -> "$n cards" },
    pvpSurrender        = "Surrender",
    pvpContinue         = "Continue",
    pvpPlayAgain        = "Play again",
    pvpGoHome           = "Home",
    pvpSurrenderDialogTitle = "Surrender?",
    pvpCancel           = "Cancel",
    pvpGotIt            = "Got it!",
    pvpTurn             = { name -> "Turn: $name" },
    pvpSelectCard       = "Select a card to play",
    pvpInDeck           = { n -> "In deck: $n" },
    pvpTaskFor          = { name -> "Challenge for $name" },
    pvpGameEnded        = "Game ended",
    pvpGameOver         = "Game over!",
    pvpForfeit          = { name -> "$name surrendered." },
    pvpAfk              = { name -> "$name was removed for inactivity." },
    pvpScore            = { n -> "$n points" },
    pvpWinner           = { name -> "Winner: $name 🎉" },
    pvpDraw             = "Draw!",
    pvpSurrenderConfirm = { name -> "$name, are you sure you want to surrender?\nYour opponent will be declared the winner." },

    shopTitle       = "Card Shop",
    shopPackNameFor = { pair -> if (pair == "he-ru") "Hebrew pack" else "English pack" },
    shopPackCards   = "5 cards per pack",
    shopOpenButton  = "Open",
    shopOpenMultiple= { n -> "Open  ($n packs)" },
    shopNoPacks     = "No packs",
    shopEarnPacks   = "Play PvE or PvP to earn a free pack",
    shopCountLabel  = "Count",
    shopHavePacks   = { n -> "Available: $n" },

    packOpeningLoading  = "Opening pack...",
    packOpeningTitle    = "✦  Pack opening  ✦",
    packOpeningProgress = { rev, total -> "$rev/$total revealed" },
    packOpeningRevealAll= "Reveal all",
    packOpeningToShop   = "To shop",
    packOpeningToHome   = "Home",

    newCardsTitle    = "🎴 New cards!",
    newCardsSubtitle = "Words learned — cards received!",
    newCardsCollect  = "Collect all",

    statsPlayerTitle     = "Player stats",
    statsProgressSection = "Progress",
    statsWordsLearned    = "Words learned",
    statsAccuracy        = "Answer accuracy",
    statsSeriesSection   = "Streak",
    statsCurrentStreakLabel = "Current",
    statsRecordLabel     = "Record",
    statsStreakDays       = { n -> "$n days" },
    statsPvpSection      = "PvP mode",
    statsPvpWins         = "Wins",
    statsPvpLosses       = "Losses",
    statsPvpDraws        = "Draws",
    statsBestPvpScore    = "Best score",

    wordStatsTitle          = "Word stats",
    wordStatsSortDifficult  = "Hardest",
    wordStatsSortEasiest    = "Easiest",
    wordStatsSortFrequent   = "Frequent",
    wordStatsSortRecent     = "Recent",
    wordStatsEmpty          = "No data yet.\nStart studying!",
    wordStatsProblemTitle   = { n -> "Problem words: $n" },
    wordStatsProblemSubtitle= "Tap to start reviewing mistakes",
    wordStatsErrors         = { pct -> "$pct% errors" },
    wordStatsEncounters     = { n -> "$n times" },

    achievementsTitle    = "Achievements",
    achievementsProgress = { got, total -> "Earned: $got / $total" },
    achievementsRemaining= { n -> "$n left" },
    achievementsAllDone  = "All earned! 🎉",
    achievementsReward   = "🏆 Reward",

    settingsTitle                  = "Settings",
    settingsProfileSection         = "Profile",
    settingsAvatarLabel            = "Avatar",
    settingsFromGallery            = "From gallery",
    settingsPlayerName             = "Player name",
    settingsCancelButton           = "Cancel",
    settingsAppearanceSection      = "Appearance",
    settingsDarkTheme              = "Dark theme",
    settingsLanguageSection        = "Languages",
    settingsTasksSection           = "Exercises",
    settingsStudyLanguage          = "Study language",
    settingsDefinitionMode         = "Definition quizzes",
    settingsFillBlankMode          = "Fill-in-blank quizzes",
    settingsQuizTypesLabel         = "Quiz types (PvE)",
    settingsQuizTypesCount         = { n, total -> "$n of $total" },
    settingsDone                   = "Done",
    settingsProblemWordsSource     = "Count problem words from",
    settingsProblemWordsSourceTitle= "Count mistakes from",
    settingsNativeLanguage         = "Native language",
    settingsChooseNativeLanguage   = "Choose native language",
    settingsStudyLanguageTitle     = "Study language",
    settingsProgressSection        = "Progress",
    settingsPlayerStats            = "📊  Player stats",
    settingsWordStats              = "📖  Word stats",
    settingsAchievements           = "🏆  Achievements",

    quizModeLabels = linkedMapOf(
        "foreign" to "In study language",
        "native"  to "In native language",
        "both"    to "Both options",
    ),
    quizTypeLabels = linkedMapOf(
        "translation" to "Translation (4 options)",
        "definition"  to "Definition",
        "fill_blank"  to "Fill in the blank",
    ),
    problemWordsSourceLabels = linkedMapOf(
        "both"     to "PvE + PvP together",
        "pve_only" to "PvE only",
        "pvp_only" to "PvP only",
    ),
)

val DeStrings = AppStrings(
    rarityCommon    = "Gewöhnlich",
    rarityUncommon  = "Ungewöhnlich",
    rarityRare      = "Selten",
    rarityEpic      = "Episch",
    rarityLegendary = "Legendär",
    rarityCommonShort    = "Gew",
    rarityUncommonShort  = "Ungew",
    rarityRareShort      = "Selt",
    rarityEpicShort      = "Epis",
    rarityLegendaryShort = "Legend",
    filterAll       = "Alle",

    homeSubtitle           = "Lerne Wörter, sammle Karten",
    homePveButton          = "Wörter lernen",
    homePvpButton          = "Match spielen (PvP)",
    homeCollectionButton   = "Kartensammlung",
    homeShopButton         = "🛒  Kartenshop",
    homeProblemWordsTitle  = { n -> "Problemwörter: $n" },
    homeProblemWordsSubtitle = "Fehler aufarbeiten?",
    homePackReady          = "Pack bereit!",

    studyTitle = "Wörter lernen",
    studyBack  = "← Zurück",

    studyNewWord           = "Neues Wort",
    studyGotIt             = "Verstanden!",
    studyQTranslation      = "Übersetzung wählen:",
    studyQDefinition       = "Definition wählen:",
    studyQDefinitionNative = "Definition wählen:",
    studyQWordFromDef      = "Wort nach Definition wählen:",
    studyQWordFromDefNative= "Wort nach Beschreibung wählen:",
    studyQFillBlank        = "Wort für die Lücke wählen:",
    studyQFillBlankNative  = "Wort für die Lücke wählen:",
    studyContinue          = "Weiter",
    studyIncorrect         = "Falsch",
    studySessionComplete   = "Sitzung abgeschlossen!",
    studyCorrectLabel      = "Richtig",
    studyIncorrectLabel    = "Fehler",
    studyNewSession        = "Neue Sitzung",
    studyBackHome          = "Startseite",
    studyNoWords           = "Keine Wörter zum Lernen.",

    setDetailStartButton = "Lernen starten",
    setDetailProgress    = { done, total -> "Gelernt: $done / $total Wörter" },

    problemWordsTitle        = "Problemwörter",
    problemWordsEmpty        = "Keine Problemwörter!\nWeiter so.",
    problemWordsBack         = "Zurück",
    problemWordsCompleteTitle= "Wiederholung abgeschlossen!",
    problemWordsCorrectLabel = "Richtig",
    problemWordsIncorrectLabel = "Fehler",
    problemWordsImproved     = { imp, total -> "Verbessert: $imp von $total Wörtern" },
    problemWordsNoImprovement= "Noch keine Verbesserung — mach weiter!",
    problemWordsRetry        = "Nochmal",

    collectionTitle     = "Sammlung",
    collectionCount     = { n -> "$n Karten" },
    collectionBuildDeck = "Deck bauen",
    collectionEmpty     = "Sammlung ist leer",

    deckBuilderTitle    = "Deck-Baukasten",
    deckBuilderSize     = { cur, max -> "$cur / $max Karten" },
    deckTabInDeck       = { n -> "Im Deck ($n)" },
    deckTabAvailable    = { n -> "Verfügbar ($n)" },
    deckEmptyDeck       = "Deck leer — Karten hinzufügen",
    deckEmptyAvailable  = "Alle Karten bereits im Deck",

    myDecksTitle              = "Meine Decks",
    myDecksCollectionLink     = "Sammlung",
    myDecksCreate             = "Deck erstellen",
    myDecksEmpty              = "Keine Decks — erstelle das erste!",
    myDecksEdit               = "Bearbeiten",
    myDecksDelete             = "Löschen",
    myDecksCreateDialogTitle  = "Neues Deck",
    myDecksCreateDialogHint   = "Deck-Name",
    myDecksCreateDialogLevel  = "Deck-Level:",
    myDecksCreateDialogConfirm= "Erstellen",
    myDecksCreateDialogCancel = "Abbrechen",
     myDecksDeleteTitle        = "Deck löschen?",
     myDecksDeleteConfirm      = { name -> "\"$name\" löschen? Diese Aktion kann nicht rückgängig gemacht werden." },
    deckCardCount             = { cur, max -> "$cur / $max Karten" },
    deckInvalidLabel          = "Zusammensetzung passt nicht zum Level",
    deckInvalidHint           = "Öffne das Deck und korrigiere die Kartenzusammensetzung",

    pvpDeckSelectTitle  = "PvP — Decks wählen",
    pvpNoDecks          = "Erstelle mindestens ein Deck vor dem Spielen",
    pvpPlayer1Label     = "Spieler 1",
    pvpPlayer2Label     = "Spieler 2",
    pvpNameHint         = "Spielername",
    pvpDeckHint         = "Deck wählen",
    pvpStartGame        = "Spiel starten",
    pvpLevelMismatch    = "Wähle Decks gleichen Levels",
    pvpDeckInvalidWarning = "Ein oder beide Decks passen nicht zu ihrem Level",
    pvpDeckCardCount    = { n -> "$n Karten" },
    pvpSurrender        = "Aufgeben",
    pvpContinue         = "Weiter",
    pvpPlayAgain        = "Nochmal spielen",
    pvpGoHome           = "Startseite",
    pvpSurrenderDialogTitle = "Aufgeben?",
    pvpCancel           = "Abbrechen",
    pvpGotIt            = "Verstanden!",
    pvpTurn             = { name -> "Zug: $name" },
    pvpSelectCard       = "Karte zum Spielen auswählen",
    pvpInDeck           = { n -> "Im Deck: $n" },
    pvpTaskFor          = { name -> "Aufgabe für $name" },
    pvpGameEnded        = "Spiel beendet",
    pvpGameOver         = "Spiel vorbei!",
    pvpForfeit          = { name -> "$name hat aufgegeben." },
    pvpAfk              = { name -> "$name wurde wegen Inaktivität entfernt." },
    pvpScore            = { n -> "$n Punkte" },
    pvpWinner           = { name -> "Gewinner: $name 🎉" },
    pvpDraw             = "Unentschieden!",
    pvpSurrenderConfirm = { name -> "$name, bist du sicher, dass du aufgeben möchtest?\nDein Gegner wird zum Sieger erklärt." },

    shopTitle       = "Kartenshop",
    shopPackNameFor = { pair -> if (pair == "he-ru") "Hebräisches Paket" else "Englisches Paket" },
    shopPackCards   = "5 Karten pro Paket",
    shopOpenButton  = "Öffnen",
    shopOpenMultiple= { n -> "Öffnen  ($n Pakete)" },
    shopNoPacks     = "Keine Pakete",
    shopEarnPacks   = "Spiele PvE oder PvP für ein kostenloses Paket",
    shopCountLabel  = "Anzahl",
    shopHavePacks   = { n -> "Verfügbar: $n" },

    packOpeningLoading  = "Paket öffnen...",
    packOpeningTitle    = "✦  Paket öffnen  ✦",
    packOpeningProgress = { rev, total -> "$rev/$total enthüllt" },
    packOpeningRevealAll= "Alle enthüllen",
    packOpeningToShop   = "Zum Shop",
    packOpeningToHome   = "Startseite",

    newCardsTitle    = "🎴 Neue Karten!",
    newCardsSubtitle = "Wörter gelernt — Karten erhalten!",
    newCardsCollect  = "Alle abholen",

    statsPlayerTitle     = "Spielerstatistik",
    statsProgressSection = "Fortschritt",
    statsWordsLearned    = "Wörter gelernt",
    statsAccuracy        = "Antwortgenauigkeit",
    statsSeriesSection   = "Serie",
    statsCurrentStreakLabel = "Aktuell",
    statsRecordLabel     = "Rekord",
    statsStreakDays       = { n -> "$n T." },
    statsPvpSection      = "PvP-Modus",
    statsPvpWins         = "Siege",
    statsPvpLosses       = "Niederlagen",
    statsPvpDraws        = "Unentschieden",
    statsBestPvpScore    = "Beste Punktzahl",

    wordStatsTitle          = "Wortstatistik",
    wordStatsSortDifficult  = "Schwierig",
    wordStatsSortEasiest    = "Leicht",
    wordStatsSortFrequent   = "Häufig",
    wordStatsSortRecent     = "Neulich",
    wordStatsEmpty          = "Noch keine Daten.\nFang an zu lernen!",
    wordStatsProblemTitle   = { n -> "Problemwörter: $n" },
    wordStatsProblemSubtitle= "Tippe, um Fehler zu wiederholen",
    wordStatsErrors         = { pct -> "$pct% Fehler" },
    wordStatsEncounters     = { n -> "$n Mal" },

    achievementsTitle    = "Errungenschaften",
    achievementsProgress = { got, total -> "Erhalten: $got / $total" },
    achievementsRemaining= { n -> "$n verbleibend" },
    achievementsAllDone  = "Alle erhalten! 🎉",
    achievementsReward   = "🏆 Belohnung",

    settingsTitle                  = "Einstellungen",
    settingsProfileSection         = "Profil",
    settingsAvatarLabel            = "Avatar",
    settingsFromGallery            = "Aus Galerie",
    settingsPlayerName             = "Spielername",
    settingsCancelButton           = "Abbrechen",
    settingsAppearanceSection      = "Darstellung",
    settingsDarkTheme              = "Dunkles Design",
    settingsLanguageSection        = "Sprachen",
    settingsTasksSection           = "Übungen",
    settingsStudyLanguage          = "Lernsprache",
    settingsDefinitionMode         = "Definitions-Quiz",
    settingsFillBlankMode          = "Lückentext-Quiz",
    settingsQuizTypesLabel         = "Quiz-Typen (PvE)",
    settingsQuizTypesCount         = { n, total -> "$n von $total" },
    settingsDone                   = "Fertig",
    settingsProblemWordsSource     = "Problemwörter zählen aus",
    settingsProblemWordsSourceTitle= "Fehler zählen aus",
    settingsNativeLanguage         = "Muttersprache",
    settingsChooseNativeLanguage   = "Muttersprache wählen",
    settingsStudyLanguageTitle     = "Lernsprache",
    settingsProgressSection        = "Fortschritt",
    settingsPlayerStats            = "📊  Spielerstatistik",
    settingsWordStats              = "📖  Wortstatistik",
    settingsAchievements           = "🏆  Errungenschaften",

    quizModeLabels = linkedMapOf(
        "foreign" to "In Lernsprache",
        "native"  to "In Muttersprache",
        "both"    to "Beide Optionen",
    ),
    quizTypeLabels = linkedMapOf(
        "translation" to "Übersetzung (4 Optionen)",
        "definition"  to "Definition",
        "fill_blank"  to "Lückentext",
    ),
    problemWordsSourceLabels = linkedMapOf(
        "both"     to "PvE + PvP zusammen",
        "pve_only" to "Nur PvE",
        "pvp_only" to "Nur PvP",
    ),
)

val FrStrings = AppStrings(
    rarityCommon    = "Commun",
    rarityUncommon  = "Peu commun",
    rarityRare      = "Rare",
    rarityEpic      = "Épique",
    rarityLegendary = "Légendaire",
    rarityCommonShort    = "Comm",
    rarityUncommonShort  = "P.comm",
    rarityRareShort      = "Rare",
    rarityEpicShort      = "Épiq",
    rarityLegendaryShort = "Légend",
    filterAll       = "Tout",

    homeSubtitle           = "Apprends des mots, collecte des cartes",
    homePveButton          = "Apprendre des mots",
    homePvpButton          = "Jouer un match (PvP)",
    homeCollectionButton   = "Collection de cartes",
    homeShopButton         = "🛒  Boutique",
    homeProblemWordsTitle  = { n -> "Mots difficiles : $n" },
    homeProblemWordsSubtitle = "Travailler ses erreurs ?",
    homePackReady          = "Pack prêt !",

    studyTitle = "Apprendre des mots",
    studyBack  = "← Retour",

    studyNewWord           = "Nouveau mot",
    studyGotIt             = "Compris !",
    studyQTranslation      = "Choisir la traduction :",
    studyQDefinition       = "Choisir la définition :",
    studyQDefinitionNative = "Choisir la définition :",
    studyQWordFromDef      = "Choisir le mot par définition :",
    studyQWordFromDefNative= "Choisir le mot par description :",
    studyQFillBlank        = "Choisir le mot pour compléter :",
    studyQFillBlankNative  = "Choisir le mot pour compléter :",
    studyContinue          = "Continuer",
    studyIncorrect         = "Incorrect",
    studySessionComplete   = "Session terminée !",
    studyCorrectLabel      = "Correct",
    studyIncorrectLabel    = "Erreurs",
    studyNewSession        = "Nouvelle session",
    studyBackHome          = "Accueil",
    studyNoWords           = "Aucun mot à apprendre.",

    setDetailStartButton = "Commencer",
    setDetailProgress    = { done, total -> "Appris : $done / $total mots" },

    problemWordsTitle        = "Mots difficiles",
    problemWordsEmpty        = "Aucun mot difficile !\nContinue comme ça.",
    problemWordsBack         = "Retour",
    problemWordsCompleteTitle= "Révision terminée !",
    problemWordsCorrectLabel = "Correct",
    problemWordsIncorrectLabel = "Erreurs",
    problemWordsImproved     = { imp, total -> "Amélioré : $imp sur $total mots" },
    problemWordsNoImprovement= "Pas encore d'amélioration — continue !",
    problemWordsRetry        = "Réessayer",

    collectionTitle     = "Collection",
    collectionCount     = { n -> "$n cartes" },
    collectionBuildDeck = "Construire un deck",
    collectionEmpty     = "La collection est vide",

    deckBuilderTitle    = "Constructeur de deck",
    deckBuilderSize     = { cur, max -> "$cur / $max cartes" },
    deckTabInDeck       = { n -> "Dans le deck ($n)" },
    deckTabAvailable    = { n -> "Disponible ($n)" },
    deckEmptyDeck       = "Deck vide — ajouter des cartes",
    deckEmptyAvailable  = "Toutes les cartes sont déjà dans le deck",

    myDecksTitle              = "Mes decks",
    myDecksCollectionLink     = "Collection",
    myDecksCreate             = "Créer un deck",
    myDecksEmpty              = "Aucun deck — créez le premier !",
    myDecksEdit               = "Modifier",
    myDecksDelete             = "Supprimer",
    myDecksCreateDialogTitle  = "Nouveau deck",
    myDecksCreateDialogHint   = "Nom du deck",
    myDecksCreateDialogLevel  = "Niveau du deck :",
    myDecksCreateDialogConfirm= "Créer",
    myDecksCreateDialogCancel = "Annuler",
     myDecksDeleteTitle        = "Supprimer le deck ?",
     myDecksDeleteConfirm      = { name -> "Supprimer « $name » ? Cette action est irréversible." },
    deckCardCount             = { cur, max -> "$cur / $max cartes" },
    deckInvalidLabel          = "La composition ne correspond pas au niveau",
    deckInvalidHint           = "Ouvrez le deck et corrigez la composition des cartes",

    pvpDeckSelectTitle  = "PvP — Choisir les decks",
    pvpNoDecks          = "Créez au moins un deck avant de jouer",
    pvpPlayer1Label     = "Joueur 1",
    pvpPlayer2Label     = "Joueur 2",
    pvpNameHint         = "Nom du joueur",
    pvpDeckHint         = "Choisir un deck",
    pvpStartGame        = "Commencer la partie",
    pvpLevelMismatch    = "Choisissez des decks du même niveau",
    pvpDeckInvalidWarning = "Un ou les deux decks ne correspondent pas à leur niveau",
    pvpDeckCardCount    = { n -> "$n cartes" },
    pvpSurrender        = "Abandonner",
    pvpContinue         = "Continuer",
    pvpPlayAgain        = "Rejouer",
    pvpGoHome           = "Accueil",
    pvpSurrenderDialogTitle = "Abandonner ?",
    pvpCancel           = "Annuler",
    pvpGotIt            = "Compris !",
    pvpTurn             = { name -> "Tour : $name" },
    pvpSelectCard       = "Choisissez une carte à jouer",
    pvpInDeck           = { n -> "Dans le deck : $n" },
    pvpTaskFor          = { name -> "Défi pour $name" },
    pvpGameEnded        = "Partie terminée",
    pvpGameOver         = "Fin de partie !",
    pvpForfeit          = { name -> "$name a abandonné." },
    pvpAfk              = { name -> "$name a été éliminé pour inactivité." },
    pvpScore            = { n -> "$n points" },
    pvpWinner           = { name -> "Gagnant : $name 🎉" },
    pvpDraw             = "Match nul !",
    pvpSurrenderConfirm = { name -> "$name, êtes-vous sûr de vouloir abandonner ?\nVotre adversaire sera déclaré vainqueur." },

    shopTitle       = "Boutique de packs",
    shopPackNameFor = { pair -> if (pair == "he-ru") "Pack hébreu" else "Pack anglais" },
    shopPackCards   = "5 cartes par pack",
    shopOpenButton  = "Ouvrir",
    shopOpenMultiple= { n -> "Ouvrir  ($n packs)" },
    shopNoPacks     = "Aucun pack",
    shopEarnPacks   = "Joue PvE ou PvP pour obtenir un pack gratuit",
    shopCountLabel  = "Quantité",
    shopHavePacks   = { n -> "Disponibles : $n" },

    packOpeningLoading  = "Ouverture du pack...",
    packOpeningTitle    = "✦  Ouverture du pack  ✦",
    packOpeningProgress = { rev, total -> "$rev/$total révélés" },
    packOpeningRevealAll= "Tout révéler",
    packOpeningToShop   = "Boutique",
    packOpeningToHome   = "Accueil",

    newCardsTitle    = "🎴 Nouvelles cartes !",
    newCardsSubtitle = "Mots appris — cartes reçues !",
    newCardsCollect  = "Tout récupérer",

    statsPlayerTitle     = "Statistiques du joueur",
    statsProgressSection = "Progression",
    statsWordsLearned    = "Mots appris",
    statsAccuracy        = "Précision des réponses",
    statsSeriesSection   = "Série",
    statsCurrentStreakLabel = "Actuelle",
    statsRecordLabel     = "Record",
    statsStreakDays       = { n -> "$n j." },
    statsPvpSection      = "Mode PvP",
    statsPvpWins         = "Victoires",
    statsPvpLosses       = "Défaites",
    statsPvpDraws        = "Nuls",
    statsBestPvpScore    = "Meilleur score",

    wordStatsTitle          = "Statistiques des mots",
    wordStatsSortDifficult  = "Difficiles",
    wordStatsSortEasiest    = "Faciles",
    wordStatsSortFrequent   = "Fréquents",
    wordStatsSortRecent     = "Récents",
    wordStatsEmpty          = "Pas encore de données.\nCommence à apprendre !",
    wordStatsProblemTitle   = { n -> "Mots difficiles : $n" },
    wordStatsProblemSubtitle= "Appuie pour commencer la révision",
    wordStatsErrors         = { pct -> "$pct% d'erreurs" },
    wordStatsEncounters     = { n -> "$n fois" },

    achievementsTitle    = "Succès",
    achievementsProgress = { got, total -> "Obtenus : $got / $total" },
    achievementsRemaining= { n -> "$n restants" },
    achievementsAllDone  = "Tous obtenus ! 🎉",
    achievementsReward   = "🏆 Récompense",

    settingsTitle                  = "Paramètres",
    settingsProfileSection         = "Profil",
    settingsAvatarLabel            = "Avatar",
    settingsFromGallery            = "De la galerie",
    settingsPlayerName             = "Nom du joueur",
    settingsCancelButton           = "Annuler",
    settingsAppearanceSection      = "Apparence",
    settingsDarkTheme              = "Thème sombre",
    settingsLanguageSection        = "Langues",
    settingsTasksSection           = "Exercices",
    settingsStudyLanguage          = "Langue d'apprentissage",
    settingsDefinitionMode         = "Quiz de définitions",
    settingsFillBlankMode          = "Quiz à trous",
    settingsQuizTypesLabel         = "Types de quiz (PvE)",
    settingsQuizTypesCount         = { n, total -> "$n sur $total" },
    settingsDone                   = "Terminé",
    settingsProblemWordsSource     = "Compter les mots difficiles depuis",
    settingsProblemWordsSourceTitle= "Compter les erreurs depuis",
    settingsNativeLanguage         = "Langue maternelle",
    settingsChooseNativeLanguage   = "Choisir la langue maternelle",
    settingsStudyLanguageTitle     = "Langue d'apprentissage",
    settingsProgressSection        = "Progression",
    settingsPlayerStats            = "📊  Statistiques du joueur",
    settingsWordStats              = "📖  Statistiques des mots",
    settingsAchievements           = "🏆  Succès",

    quizModeLabels = linkedMapOf(
        "foreign" to "En langue étudiée",
        "native"  to "En langue maternelle",
        "both"    to "Les deux options",
    ),
    quizTypeLabels = linkedMapOf(
        "translation" to "Traduction (4 options)",
        "definition"  to "Définition",
        "fill_blank"  to "Texte à trous",
    ),
    problemWordsSourceLabels = linkedMapOf(
        "both"     to "PvE + PvP ensemble",
        "pve_only" to "PvE seulement",
        "pvp_only" to "PvP seulement",
    ),
)

val EsStrings = AppStrings(
    rarityCommon    = "Común",
    rarityUncommon  = "Poco común",
    rarityRare      = "Raro",
    rarityEpic      = "Épico",
    rarityLegendary = "Legendario",
    rarityCommonShort    = "Común",
    rarityUncommonShort  = "P.com",
    rarityRareShort      = "Raro",
    rarityEpicShort      = "Épic",
    rarityLegendaryShort = "Legend",
    filterAll       = "Todos",

    homeSubtitle           = "Aprende palabras, colecciona cartas",
    homePveButton          = "Aprender palabras",
    homePvpButton          = "Jugar partida (PvP)",
    homeCollectionButton   = "Colección de cartas",
    homeShopButton         = "🛒  Tienda",
    homeProblemWordsTitle  = { n -> "Palabras problema: $n" },
    homeProblemWordsSubtitle = "¿Trabajar los errores?",
    homePackReady          = "¡Pack listo!",

    studyTitle = "Aprender palabras",
    studyBack  = "← Atrás",

    studyNewWord           = "Nueva palabra",
    studyGotIt             = "¡Entendido!",
    studyQTranslation      = "Elige la traducción:",
    studyQDefinition       = "Elige la definición:",
    studyQDefinitionNative = "Elige la definición:",
    studyQWordFromDef      = "Elige la palabra por definición:",
    studyQWordFromDefNative= "Elige la palabra por descripción:",
    studyQFillBlank        = "Elige la palabra para el hueco:",
    studyQFillBlankNative  = "Elige la palabra para el hueco:",
    studyContinue          = "Continuar",
    studyIncorrect         = "Incorrecto",
    studySessionComplete   = "¡Sesión completada!",
    studyCorrectLabel      = "Correcto",
    studyIncorrectLabel    = "Errores",
    studyNewSession        = "Nueva sesión",
    studyBackHome          = "Inicio",
    studyNoWords           = "No hay palabras para estudiar.",

    setDetailStartButton = "Empezar",
    setDetailProgress    = { done, total -> "Aprendido: $done / $total palabras" },

    problemWordsTitle        = "Palabras problema",
    problemWordsEmpty        = "¡Sin palabras problema!\nSigue así.",
    problemWordsBack         = "Atrás",
    problemWordsCompleteTitle= "¡Repaso completado!",
    problemWordsCorrectLabel = "Correcto",
    problemWordsIncorrectLabel = "Errores",
    problemWordsImproved     = { imp, total -> "Mejorado: $imp de $total palabras" },
    problemWordsNoImprovement= "Sin mejora aún — ¡sigue intentando!",
    problemWordsRetry        = "Intentar de nuevo",

    collectionTitle     = "Colección",
    collectionCount     = { n -> "$n cartas" },
    collectionBuildDeck = "Construir mazo",
    collectionEmpty     = "La colección está vacía",

    deckBuilderTitle    = "Constructor de mazos",
    deckBuilderSize     = { cur, max -> "$cur / $max cartas" },
    deckTabInDeck       = { n -> "En el mazo ($n)" },
    deckTabAvailable    = { n -> "Disponible ($n)" },
    deckEmptyDeck       = "Mazo vacío — añadir cartas",
    deckEmptyAvailable  = "Todas las cartas ya están en el mazo",

    myDecksTitle              = "Mis mazos",
    myDecksCollectionLink     = "Colección",
    myDecksCreate             = "Crear mazo",
    myDecksEmpty              = "No hay mazos — ¡crea el primero!",
    myDecksEdit               = "Editar",
    myDecksDelete             = "Eliminar",
    myDecksCreateDialogTitle  = "Nuevo mazo",
    myDecksCreateDialogHint   = "Nombre del mazo",
    myDecksCreateDialogLevel  = "Nivel del mazo:",
    myDecksCreateDialogConfirm= "Crear",
    myDecksCreateDialogCancel = "Cancelar",
     myDecksDeleteTitle        = "¿Eliminar mazo?",
     myDecksDeleteConfirm      = { name -> "¿Eliminar «$name»? Esta acción no se puede deshacer." },
    deckCardCount             = { cur, max -> "$cur / $max cartas" },
    deckInvalidLabel          = "La composición no corresponde al nivel",
    deckInvalidHint           = "Abre el mazo y corrige la composición de cartas",

    pvpDeckSelectTitle  = "PvP — Elegir mazos",
    pvpNoDecks          = "Crea al menos un mazo antes de jugar",
    pvpPlayer1Label     = "Jugador 1",
    pvpPlayer2Label     = "Jugador 2",
    pvpNameHint         = "Nombre del jugador",
    pvpDeckHint         = "Elegir mazo",
    pvpStartGame        = "Iniciar partida",
    pvpLevelMismatch    = "Elige mazos del mismo nivel",
    pvpDeckInvalidWarning = "Uno o ambos mazos no corresponden a su nivel",
    pvpDeckCardCount    = { n -> "$n cartas" },
    pvpSurrender        = "Rendirse",
    pvpContinue         = "Continuar",
    pvpPlayAgain        = "Jugar de nuevo",
    pvpGoHome           = "Inicio",
    pvpSurrenderDialogTitle = "¿Rendirse?",
    pvpCancel           = "Cancelar",
    pvpGotIt            = "¡Entendido!",
    pvpTurn             = { name -> "Turno: $name" },
    pvpSelectCard       = "Selecciona una carta para jugar",
    pvpInDeck           = { n -> "En el mazo: $n" },
    pvpTaskFor          = { name -> "Desafío para $name" },
    pvpGameEnded        = "Juego terminado",
    pvpGameOver         = "¡Fin del juego!",
    pvpForfeit          = { name -> "$name se rindió." },
    pvpAfk              = { name -> "$name fue eliminado por inactividad." },
    pvpScore            = { n -> "$n puntos" },
    pvpWinner           = { name -> "Ganador: $name 🎉" },
    pvpDraw             = "¡Empate!",
    pvpSurrenderConfirm = { name -> "$name, ¿estás seguro de que quieres rendirte?\nTu oponente será declarado ganador." },

    shopTitle       = "Tienda de packs",
    shopPackNameFor = { pair -> if (pair == "he-ru") "Pack de hebreo" else "Pack de inglés" },
    shopPackCards   = "5 cartas por pack",
    shopOpenButton  = "Abrir",
    shopOpenMultiple= { n -> "Abrir  ($n packs)" },
    shopNoPacks     = "Sin packs",
    shopEarnPacks   = "Juega PvE o PvP para conseguir un pack gratis",
    shopCountLabel  = "Cantidad",
    shopHavePacks   = { n -> "Disponibles: $n" },

    packOpeningLoading  = "Abriendo pack...",
    packOpeningTitle    = "✦  Apertura de pack  ✦",
    packOpeningProgress = { rev, total -> "$rev/$total revelados" },
    packOpeningRevealAll= "Revelar todo",
    packOpeningToShop   = "Tienda",
    packOpeningToHome   = "Inicio",

    newCardsTitle    = "🎴 ¡Nuevas cartas!",
    newCardsSubtitle = "¡Palabras aprendidas — cartas recibidas!",
    newCardsCollect  = "Recoger todo",

    statsPlayerTitle     = "Estadísticas del jugador",
    statsProgressSection = "Progreso",
    statsWordsLearned    = "Palabras aprendidas",
    statsAccuracy        = "Precisión de respuestas",
    statsSeriesSection   = "Racha",
    statsCurrentStreakLabel = "Actual",
    statsRecordLabel     = "Récord",
    statsStreakDays       = { n -> "$n días" },
    statsPvpSection      = "Modo PvP",
    statsPvpWins         = "Victorias",
    statsPvpLosses       = "Derrotas",
    statsPvpDraws        = "Empates",
    statsBestPvpScore    = "Mejor puntuación",

    wordStatsTitle          = "Estadísticas de palabras",
    wordStatsSortDifficult  = "Difíciles",
    wordStatsSortEasiest    = "Fáciles",
    wordStatsSortFrequent   = "Frecuentes",
    wordStatsSortRecent     = "Recientes",
    wordStatsEmpty          = "Sin datos aún.\n¡Empieza a estudiar!",
    wordStatsProblemTitle   = { n -> "Palabras problema: $n" },
    wordStatsProblemSubtitle= "Toca para repasar errores",
    wordStatsErrors         = { pct -> "$pct% errores" },
    wordStatsEncounters     = { n -> "$n veces" },

    achievementsTitle    = "Logros",
    achievementsProgress = { got, total -> "Obtenidos: $got / $total" },
    achievementsRemaining= { n -> "$n restantes" },
    achievementsAllDone  = "¡Todos obtenidos! 🎉",
    achievementsReward   = "🏆 Recompensa",

    settingsTitle                  = "Ajustes",
    settingsProfileSection         = "Perfil",
    settingsAvatarLabel            = "Avatar",
    settingsFromGallery            = "De la galería",
    settingsPlayerName             = "Nombre del jugador",
    settingsCancelButton           = "Cancelar",
    settingsAppearanceSection      = "Apariencia",
    settingsDarkTheme              = "Tema oscuro",
    settingsLanguageSection        = "Idiomas",
    settingsTasksSection           = "Ejercicios",
    settingsStudyLanguage          = "Idioma de estudio",
    settingsDefinitionMode         = "Quiz de definiciones",
    settingsFillBlankMode          = "Quiz de relleno",
    settingsQuizTypesLabel         = "Tipos de quiz (PvE)",
    settingsQuizTypesCount         = { n, total -> "$n de $total" },
    settingsDone                   = "Listo",
    settingsProblemWordsSource     = "Contar palabras problema desde",
    settingsProblemWordsSourceTitle= "Contar errores desde",
    settingsNativeLanguage         = "Idioma nativo",
    settingsChooseNativeLanguage   = "Elegir idioma nativo",
    settingsStudyLanguageTitle     = "Idioma de estudio",
    settingsProgressSection        = "Progreso",
    settingsPlayerStats            = "📊  Estadísticas del jugador",
    settingsWordStats              = "📖  Estadísticas de palabras",
    settingsAchievements           = "🏆  Logros",

    quizModeLabels = linkedMapOf(
        "foreign" to "En idioma estudiado",
        "native"  to "En idioma nativo",
        "both"    to "Ambas opciones",
    ),
    quizTypeLabels = linkedMapOf(
        "translation" to "Traducción (4 opciones)",
        "definition"  to "Definición",
        "fill_blank"  to "Rellenar el hueco",
    ),
    problemWordsSourceLabels = linkedMapOf(
        "both"     to "PvE + PvP juntos",
        "pve_only" to "Solo PvE",
        "pvp_only" to "Solo PvP",
    ),
)

val ZhStrings = AppStrings(
    rarityCommon    = "普通",
    rarityUncommon  = "罕见",
    rarityRare      = "稀有",
    rarityEpic      = "史诗",
    rarityLegendary = "传说",
    rarityCommonShort    = "普通",
    rarityUncommonShort  = "罕见",
    rarityRareShort      = "稀有",
    rarityEpicShort      = "史诗",
    rarityLegendaryShort = "传说",
    filterAll       = "全部",

    homeSubtitle           = "学习单词，收集卡片",
    homePveButton          = "学习单词",
    homePvpButton          = "对战 (PvP)",
    homeCollectionButton   = "卡片收藏",
    homeShopButton         = "🛒  卡包商店",
    homeProblemWordsTitle  = { n -> "问题单词：$n" },
    homeProblemWordsSubtitle = "练习错误单词？",
    homePackReady          = "卡包准备好了！",

    studyTitle = "学习单词",
    studyBack  = "← 返回",

    studyNewWord           = "新单词",
    studyGotIt             = "明白了！",
    studyQTranslation      = "选择翻译：",
    studyQDefinition       = "选择定义：",
    studyQDefinitionNative = "选择定义：",
    studyQWordFromDef      = "根据定义选择单词：",
    studyQWordFromDefNative= "根据描述选择单词：",
    studyQFillBlank        = "选择填空单词：",
    studyQFillBlankNative  = "选择填空单词：",
    studyContinue          = "继续",
    studyIncorrect         = "错误",
    studySessionComplete   = "学习结束！",
    studyCorrectLabel      = "正确",
    studyIncorrectLabel    = "错误",
    studyNewSession        = "新学习",
    studyBackHome          = "主页",
    studyNoWords           = "没有单词可以学习。",

    setDetailStartButton = "开始学习",
    setDetailProgress    = { done, total -> "已学：$done / $total 个单词" },

    problemWordsTitle        = "问题单词",
    problemWordsEmpty        = "没有问题单词！\n继续保持。",
    problemWordsBack         = "返回",
    problemWordsCompleteTitle= "复习完成！",
    problemWordsCorrectLabel = "正确",
    problemWordsIncorrectLabel = "错误",
    problemWordsImproved     = { imp, total -> "改进：$total 个单词中的 $imp 个" },
    problemWordsNoImprovement= "还没有改进 — 继续努力！",
    problemWordsRetry        = "再来一次",

    collectionTitle     = "收藏",
    collectionCount     = { n -> "$n 张卡片" },
    collectionBuildDeck = "构建套牌",
    collectionEmpty     = "收藏为空",

    deckBuilderTitle    = "套牌构建器",
    deckBuilderSize     = { cur, max -> "$cur / $max 张卡片" },
    deckTabInDeck       = { n -> "套牌中 ($n)" },
    deckTabAvailable    = { n -> "可用 ($n)" },
    deckEmptyDeck       = "套牌为空 — 添加卡片",
    deckEmptyAvailable  = "所有卡片已在套牌中",

    myDecksTitle              = "我的套牌",
    myDecksCollectionLink     = "收藏",
    myDecksCreate             = "创建套牌",
    myDecksEmpty              = "没有套牌 — 创建第一个！",
    myDecksEdit               = "编辑",
    myDecksDelete             = "删除",
    myDecksCreateDialogTitle  = "新套牌",
    myDecksCreateDialogHint   = "套牌名称",
    myDecksCreateDialogLevel  = "套牌等级：",
    myDecksCreateDialogConfirm= "创建",
    myDecksCreateDialogCancel = "取消",
     myDecksDeleteTitle        = "删除卡组？",
     myDecksDeleteConfirm      = { name -> "删除「$name」？此操作无法撤销。" },
    deckCardCount             = { cur, max -> "$cur / $max 张卡片" },
    deckInvalidLabel          = "套牌组成与等级不符",
    deckInvalidHint           = "打开套牌并修正卡牌组成",

    pvpDeckSelectTitle  = "PvP — 选择套牌",
    pvpNoDecks          = "游戏前至少创建一个套牌",
    pvpPlayer1Label     = "玩家 1",
    pvpPlayer2Label     = "玩家 2",
    pvpNameHint         = "玩家名称",
    pvpDeckHint         = "选择套牌",
    pvpStartGame        = "开始游戏",
    pvpLevelMismatch    = "请选择相同等级的套牌",
    pvpDeckInvalidWarning = "一个或两个套牌与其等级不符",
    pvpDeckCardCount    = { n -> "$n 张卡片" },
    pvpSurrender        = "认输",
    pvpContinue         = "继续",
    pvpPlayAgain        = "再玩一次",
    pvpGoHome           = "主页",
    pvpSurrenderDialogTitle = "认输？",
    pvpCancel           = "取消",
    pvpGotIt            = "明白了！",
    pvpTurn             = { name -> "轮到：$name" },
    pvpSelectCard       = "选择一张卡片出牌",
    pvpInDeck           = { n -> "套牌中：$n" },
    pvpTaskFor          = { name -> "$name 的挑战" },
    pvpGameEnded        = "游戏结束",
    pvpGameOver         = "游戏结束！",
    pvpForfeit          = { name -> "$name 认输了。" },
    pvpAfk              = { name -> "$name 因不活跃被淘汰。" },
    pvpScore            = { n -> "$n 分" },
    pvpWinner           = { name -> "获胜者：$name 🎉" },
    pvpDraw             = "平局！",
    pvpSurrenderConfirm = { name -> "$name，您确定要认输吗？\n您的对手将被宣布为获胜者。" },

    shopTitle       = "卡包商店",
    shopPackNameFor = { pair -> if (pair == "he-ru") "希伯来语卡包" else "英语卡包" },
    shopPackCards   = "每包 5 张卡片",
    shopOpenButton  = "打开",
    shopOpenMultiple= { n -> "打开（$n 个卡包）" },
    shopNoPacks     = "没有卡包",
    shopEarnPacks   = "通过 PvE 或 PvP 获取免费卡包",
    shopCountLabel  = "数量",
    shopHavePacks   = { n -> "可用: $n" },

    packOpeningLoading  = "正在打开卡包...",
    packOpeningTitle    = "✦  开包  ✦",
    packOpeningProgress = { rev, total -> "$rev/$total 已揭示" },
    packOpeningRevealAll= "全部揭示",
    packOpeningToShop   = "前往商店",
    packOpeningToHome   = "主页",

    newCardsTitle    = "🎴 新卡片！",
    newCardsSubtitle = "单词已学会 — 卡片已获得！",
    newCardsCollect  = "全部领取",

    statsPlayerTitle     = "玩家统计",
    statsProgressSection = "进度",
    statsWordsLearned    = "已学单词",
    statsAccuracy        = "答题准确率",
    statsSeriesSection   = "连续",
    statsCurrentStreakLabel = "当前",
    statsRecordLabel     = "记录",
    statsStreakDays       = { n -> "$n 天" },
    statsPvpSection      = "PvP 模式",
    statsPvpWins         = "胜利",
    statsPvpLosses       = "失败",
    statsPvpDraws        = "平局",
    statsBestPvpScore    = "最高分",

    wordStatsTitle          = "单词统计",
    wordStatsSortDifficult  = "最难",
    wordStatsSortEasiest    = "最易",
    wordStatsSortFrequent   = "最频繁",
    wordStatsSortRecent     = "最近",
    wordStatsEmpty          = "暂无数据。\n开始学习吧！",
    wordStatsProblemTitle   = { n -> "问题单词：$n" },
    wordStatsProblemSubtitle= "点击开始复习错误",
    wordStatsErrors         = { pct -> "错误率 $pct%" },
    wordStatsEncounters     = { n -> "$n 次" },

    achievementsTitle    = "成就",
    achievementsProgress = { got, total -> "已获得：$got / $total" },
    achievementsRemaining= { n -> "剩余 $n 个" },
    achievementsAllDone  = "全部获得！🎉",
    achievementsReward   = "🏆 奖励",

    settingsTitle                  = "设置",
    settingsProfileSection         = "个人资料",
    settingsAvatarLabel            = "头像",
    settingsFromGallery            = "从相册",
    settingsPlayerName             = "玩家名称",
    settingsCancelButton           = "取消",
    settingsAppearanceSection      = "外观",
    settingsDarkTheme              = "深色主题",
    settingsLanguageSection        = "语言",
    settingsTasksSection           = "练习",
    settingsStudyLanguage          = "学习语言",
    settingsDefinitionMode         = "定义测验",
    settingsFillBlankMode          = "填空测验",
    settingsQuizTypesLabel         = "测验类型 (PvE)",
    settingsQuizTypesCount         = { n, total -> "$n / $total" },
    settingsDone                   = "完成",
    settingsProblemWordsSource     = "问题单词来源",
    settingsProblemWordsSourceTitle= "错误来源",
    settingsNativeLanguage         = "母语",
    settingsChooseNativeLanguage   = "选择母语",
    settingsStudyLanguageTitle     = "学习语言",
    settingsProgressSection        = "进度",
    settingsPlayerStats            = "📊  玩家统计",
    settingsWordStats              = "📖  单词统计",
    settingsAchievements           = "🏆  成就",

    quizModeLabels = linkedMapOf(
        "foreign" to "用学习语言",
        "native"  to "用母语",
        "both"    to "两种语言",
    ),
    quizTypeLabels = linkedMapOf(
        "translation" to "翻译（4个选项）",
        "definition"  to "定义",
        "fill_blank"  to "填空",
    ),
    problemWordsSourceLabels = linkedMapOf(
        "both"     to "PvE + PvP 合计",
        "pve_only" to "仅 PvE",
        "pvp_only" to "仅 PvP",
    ),
)

val JaStrings = AppStrings(
    rarityCommon    = "コモン",
    rarityUncommon  = "アンコモン",
    rarityRare      = "レア",
    rarityEpic      = "エピック",
    rarityLegendary = "レジェンダリー",
    rarityCommonShort    = "コモン",
    rarityUncommonShort  = "アンコ",
    rarityRareShort      = "レア",
    rarityEpicShort      = "エピ",
    rarityLegendaryShort = "レジェン",
    filterAll       = "すべて",

    homeSubtitle           = "単語を学び、カードを集めよう",
    homePveButton          = "単語を学ぶ",
    homePvpButton          = "対戦する (PvP)",
    homeCollectionButton   = "カードコレクション",
    homeShopButton         = "🛒  カードショップ",
    homeProblemWordsTitle  = { n -> "問題単語：$n" },
    homeProblemWordsSubtitle = "ミスを復習しますか？",
    homePackReady          = "パック準備完了！",

    studyTitle = "単語を学ぶ",
    studyBack  = "← 戻る",

    studyNewWord           = "新しい単語",
    studyGotIt             = "わかった！",
    studyQTranslation      = "翻訳を選んでください：",
    studyQDefinition       = "定義を選んでください：",
    studyQDefinitionNative = "定義を選んでください：",
    studyQWordFromDef      = "定義から単語を選んでください：",
    studyQWordFromDefNative= "説明から単語を選んでください：",
    studyQFillBlank        = "空欄に入る単語を選んでください：",
    studyQFillBlankNative  = "空欄に入る単語を選んでください：",
    studyContinue          = "続ける",
    studyIncorrect         = "不正解",
    studySessionComplete   = "セッション完了！",
    studyCorrectLabel      = "正解",
    studyIncorrectLabel    = "ミス",
    studyNewSession        = "新しいセッション",
    studyBackHome          = "ホーム",
    studyNoWords           = "学ぶ単語がありません。",

    setDetailStartButton = "学習を始める",
    setDetailProgress    = { done, total -> "学習済み：$done / $total 単語" },

    problemWordsTitle        = "問題単語",
    problemWordsEmpty        = "問題単語なし！\nその調子で続けよう。",
    problemWordsBack         = "戻る",
    problemWordsCompleteTitle= "復習完了！",
    problemWordsCorrectLabel = "正解",
    problemWordsIncorrectLabel = "ミス",
    problemWordsImproved     = { imp, total -> "改善：$total 単語中 $imp 単語" },
    problemWordsNoImprovement= "まだ改善なし — 続けよう！",
    problemWordsRetry        = "もう一度",

    collectionTitle     = "コレクション",
    collectionCount     = { n -> "カード $n 枚" },
    collectionBuildDeck = "デッキを作る",
    collectionEmpty     = "コレクションが空です",

    deckBuilderTitle    = "デッキビルダー",
    deckBuilderSize     = { cur, max -> "$cur / $max 枚" },
    deckTabInDeck       = { n -> "デッキ内 ($n)" },
    deckTabAvailable    = { n -> "利用可能 ($n)" },
    deckEmptyDeck       = "デッキが空 — カードを追加",
    deckEmptyAvailable  = "全カードがデッキに入っています",

    myDecksTitle              = "マイデッキ",
    myDecksCollectionLink     = "コレクション",
    myDecksCreate             = "デッキを作成",
    myDecksEmpty              = "デッキなし — 最初のデッキを作ろう！",
    myDecksEdit               = "編集",
    myDecksDelete             = "削除",
    myDecksCreateDialogTitle  = "新しいデッキ",
    myDecksCreateDialogHint   = "デッキ名",
    myDecksCreateDialogLevel  = "デッキレベル：",
    myDecksCreateDialogConfirm= "作成",
    myDecksCreateDialogCancel = "キャンセル",
     myDecksDeleteTitle        = "デッキを削除？",
     myDecksDeleteConfirm      = { name -> "「$name」を削除しますか？この操作は元に戻せません。" },
    deckCardCount             = { cur, max -> "$cur / $max 枚" },
    deckInvalidLabel          = "構成がレベルに合っていません",
    deckInvalidHint           = "デッキを開いてカード構成を修正してください",

    pvpDeckSelectTitle  = "PvP — デッキ選択",
    pvpNoDecks          = "プレイ前にデッキを作成してください",
    pvpPlayer1Label     = "プレイヤー1",
    pvpPlayer2Label     = "プレイヤー2",
    pvpNameHint         = "プレイヤー名",
    pvpDeckHint         = "デッキを選択",
    pvpStartGame        = "ゲーム開始",
    pvpLevelMismatch    = "同じレベルのデッキを選んでください",
    pvpDeckInvalidWarning = "一方または両方のデッキがレベルに合っていません",
    pvpDeckCardCount    = { n -> "$n 枚" },
    pvpSurrender        = "降参",
    pvpContinue         = "続ける",
    pvpPlayAgain        = "もう一度プレイ",
    pvpGoHome           = "ホーム",
    pvpSurrenderDialogTitle = "降参しますか？",
    pvpCancel           = "キャンセル",
    pvpGotIt            = "わかった！",
    pvpTurn             = { name -> "ターン：$name" },
    pvpSelectCard       = "プレイするカードを選択",
    pvpInDeck           = { n -> "デッキに：$n" },
    pvpTaskFor          = { name -> "$name へのチャレンジ" },
    pvpGameEnded        = "ゲーム終了",
    pvpGameOver         = "ゲームオーバー！",
    pvpForfeit          = { name -> "$name が降参しました。" },
    pvpAfk              = { name -> "$name が非アクティブのため除外されました。" },
    pvpScore            = { n -> "$n ポイント" },
    pvpWinner           = { name -> "勝者：$name 🎉" },
    pvpDraw             = "引き分け！",
    pvpSurrenderConfirm = { name -> "$name、本当に降参しますか？\n相手の勝利となります。" },

    shopTitle       = "カードショップ",
    shopPackNameFor = { pair -> if (pair == "he-ru") "ヘブライ語パック" else "英語パック" },
    shopPackCards   = "1パック5枚",
    shopOpenButton  = "開ける",
    shopOpenMultiple= { n -> "開ける（$n パック）" },
    shopNoPacks     = "パックなし",
    shopEarnPacks   = "PvE または PvP をプレイして無料パックをゲット",
    shopCountLabel  = "数量",
    shopHavePacks   = { n -> "利用可能: $n" },

    packOpeningLoading  = "パックを開封中...",
    packOpeningTitle    = "✦  パック開封  ✦",
    packOpeningProgress = { rev, total -> "$rev/$total 公開済み" },
    packOpeningRevealAll= "すべて公開",
    packOpeningToShop   = "ショップへ",
    packOpeningToHome   = "ホーム",

    newCardsTitle    = "🎴 新しいカード！",
    newCardsSubtitle = "単語習得 — カード獲得！",
    newCardsCollect  = "すべて受け取る",

    statsPlayerTitle     = "プレイヤー統計",
    statsProgressSection = "進捗",
    statsWordsLearned    = "学習単語数",
    statsAccuracy        = "正答率",
    statsSeriesSection   = "連続記録",
    statsCurrentStreakLabel = "現在",
    statsRecordLabel     = "記録",
    statsStreakDays       = { n -> "$n 日" },
    statsPvpSection      = "PvP モード",
    statsPvpWins         = "勝利",
    statsPvpLosses       = "敗北",
    statsPvpDraws        = "引き分け",
    statsBestPvpScore    = "最高スコア",

    wordStatsTitle          = "単語統計",
    wordStatsSortDifficult  = "難しい",
    wordStatsSortEasiest    = "易しい",
    wordStatsSortFrequent   = "頻繁",
    wordStatsSortRecent     = "最近",
    wordStatsEmpty          = "まだデータなし。\n学習を始めよう！",
    wordStatsProblemTitle   = { n -> "問題単語：$n" },
    wordStatsProblemSubtitle= "タップしてミスを復習",
    wordStatsErrors         = { pct -> "エラー率 $pct%" },
    wordStatsEncounters     = { n -> "$n 回" },

    achievementsTitle    = "実績",
    achievementsProgress = { got, total -> "獲得済み：$got / $total" },
    achievementsRemaining= { n -> "残り $n 個" },
    achievementsAllDone  = "全部獲得！🎉",
    achievementsReward   = "🏆 報酬",

    settingsTitle                  = "設定",
    settingsProfileSection         = "プロフィール",
    settingsAvatarLabel            = "アバター",
    settingsFromGallery            = "ギャラリーから",
    settingsPlayerName             = "プレイヤー名",
    settingsCancelButton           = "キャンセル",
    settingsAppearanceSection      = "外観",
    settingsDarkTheme              = "ダークテーマ",
    settingsLanguageSection        = "言語",
    settingsTasksSection           = "練習",
    settingsStudyLanguage          = "学習言語",
    settingsDefinitionMode         = "定義クイズ",
    settingsFillBlankMode          = "穴埋めクイズ",
    settingsQuizTypesLabel         = "クイズタイプ (PvE)",
    settingsQuizTypesCount         = { n, total -> "$n / $total" },
    settingsDone                   = "完了",
    settingsProblemWordsSource     = "問題単語の集計元",
    settingsProblemWordsSourceTitle= "ミスの集計元",
    settingsNativeLanguage         = "母国語",
    settingsChooseNativeLanguage   = "母国語を選択",
    settingsStudyLanguageTitle     = "学習言語",
    settingsProgressSection        = "進捗",
    settingsPlayerStats            = "📊  プレイヤー統計",
    settingsWordStats              = "📖  単語統計",
    settingsAchievements           = "🏆  実績",

    quizModeLabels = linkedMapOf(
        "foreign" to "学習言語で",
        "native"  to "母国語で",
        "both"    to "両方",
    ),
    quizTypeLabels = linkedMapOf(
        "translation" to "翻訳（4択）",
        "definition"  to "定義",
        "fill_blank"  to "穴埋め",
    ),
    problemWordsSourceLabels = linkedMapOf(
        "both"     to "PvE + PvP 合計",
        "pve_only" to "PvE のみ",
        "pvp_only" to "PvP のみ",
    ),
)

val ArStrings = AppStrings(
    rarityCommon    = "عادي",
    rarityUncommon  = "غير شائع",
    rarityRare      = "نادر",
    rarityEpic      = "ملحمي",
    rarityLegendary = "أسطوري",
    rarityCommonShort    = "عادي",
    rarityUncommonShort  = "غ.شائع",
    rarityRareShort      = "نادر",
    rarityEpicShort      = "ملحمي",
    rarityLegendaryShort = "أسطوري",
    filterAll       = "الكل",

    homeSubtitle           = "تعلّم الكلمات، اجمع البطاقات",
    homePveButton          = "تعلّم الكلمات",
    homePvpButton          = "العب مباراة (PvP)",
    homeCollectionButton   = "مجموعة البطاقات",
    homeShopButton         = "🛒  المتجر",
    homeProblemWordsTitle  = { n -> "كلمات صعبة: $n" },
    homeProblemWordsSubtitle = "مراجعة الأخطاء؟",
    homePackReady          = "الحزمة جاهزة!",

    studyTitle = "تعلّم الكلمات",
    studyBack  = "← رجوع",

    studyNewWord           = "كلمة جديدة",
    studyGotIt             = "فهمت!",
    studyQTranslation      = "اختر الترجمة:",
    studyQDefinition       = "اختر التعريف:",
    studyQDefinitionNative = "اختر التعريف:",
    studyQWordFromDef      = "اختر الكلمة من التعريف:",
    studyQWordFromDefNative= "اختر الكلمة من الوصف:",
    studyQFillBlank        = "اختر الكلمة للفراغ:",
    studyQFillBlankNative  = "اختر الكلمة للفراغ:",
    studyContinue          = "متابعة",
    studyIncorrect         = "خطأ",
    studySessionComplete   = "انتهت الجلسة!",
    studyCorrectLabel      = "صحيح",
    studyIncorrectLabel    = "أخطاء",
    studyNewSession        = "جلسة جديدة",
    studyBackHome          = "الرئيسية",
    studyNoWords           = "لا توجد كلمات للتعلّم.",

    setDetailStartButton = "ابدأ التعلّم",
    setDetailProgress    = { done, total -> "تم تعلّم: $done / $total كلمات" },

    problemWordsTitle        = "الكلمات الصعبة",
    problemWordsEmpty        = "لا توجد كلمات صعبة!\nاستمر هكذا.",
    problemWordsBack         = "رجوع",
    problemWordsCompleteTitle= "انتهت المراجعة!",
    problemWordsCorrectLabel = "صحيح",
    problemWordsIncorrectLabel = "أخطاء",
    problemWordsImproved     = { imp, total -> "تحسّن: $imp من $total كلمات" },
    problemWordsNoImprovement= "لا تحسّن بعد — استمر!",
    problemWordsRetry        = "حاول مرة أخرى",

    collectionTitle     = "المجموعة",
    collectionCount     = { n -> "$n بطاقات" },
    collectionBuildDeck = "بناء المجموعة",
    collectionEmpty     = "المجموعة فارغة",

    deckBuilderTitle    = "منشئ المجموعة",
    deckBuilderSize     = { cur, max -> "$cur / $max بطاقات" },
    deckTabInDeck       = { n -> "في المجموعة ($n)" },
    deckTabAvailable    = { n -> "متاح ($n)" },
    deckEmptyDeck       = "المجموعة فارغة — أضف بطاقات",
    deckEmptyAvailable  = "جميع البطاقات في المجموعة بالفعل",

    myDecksTitle              = "مجموعاتي",
    myDecksCollectionLink     = "المجموعة",
    myDecksCreate             = "إنشاء مجموعة",
    myDecksEmpty              = "لا توجد مجموعات — أنشئ الأولى!",
    myDecksEdit               = "تعديل",
    myDecksDelete             = "حذف",
    myDecksCreateDialogTitle  = "مجموعة جديدة",
    myDecksCreateDialogHint   = "اسم المجموعة",
    myDecksCreateDialogLevel  = "مستوى المجموعة:",
    myDecksCreateDialogConfirm= "إنشاء",
    myDecksCreateDialogCancel = "إلغاء",
     myDecksDeleteTitle        = "حذف المجموعة؟",
     myDecksDeleteConfirm      = { name -> "حذف «$name»؟ لا يمكن التراجع عن هذا الإجراء." },
    deckCardCount             = { cur, max -> "$cur / $max بطاقات" },
    deckInvalidLabel          = "التركيبة لا تتوافق مع المستوى",
    deckInvalidHint           = "افتح المجموعة وصحح تركيبة البطاقات",

    pvpDeckSelectTitle  = "PvP — اختر المجموعات",
    pvpNoDecks          = "أنشئ مجموعة واحدة على الأقل قبل اللعب",
    pvpPlayer1Label     = "اللاعب 1",
    pvpPlayer2Label     = "اللاعب 2",
    pvpNameHint         = "اسم اللاعب",
    pvpDeckHint         = "اختر مجموعة",
    pvpStartGame        = "ابدأ اللعبة",
    pvpLevelMismatch    = "اختر مجموعات بنفس المستوى",
    pvpDeckInvalidWarning = "مجموعة واحدة أو كلتاهما لا تتوافق مع مستواها",
    pvpDeckCardCount    = { n -> "$n بطاقات" },
    pvpSurrender        = "استسلام",
    pvpContinue         = "متابعة",
    pvpPlayAgain        = "العب مرة أخرى",
    pvpGoHome           = "الرئيسية",
    pvpSurrenderDialogTitle = "استسلام؟",
    pvpCancel           = "إلغاء",
    pvpGotIt            = "فهمت!",
    pvpTurn             = { name -> "دور: $name" },
    pvpSelectCard       = "اختر بطاقة للعب",
    pvpInDeck           = { n -> "في المجموعة: $n" },
    pvpTaskFor          = { name -> "تحدي لـ$name" },
    pvpGameEnded        = "انتهت اللعبة",
    pvpGameOver         = "انتهت اللعبة!",
    pvpForfeit          = { name -> "$name استسلم." },
    pvpAfk              = { name -> "تم إقصاء $name بسبب عدم النشاط." },
    pvpScore            = { n -> "$n نقاط" },
    pvpWinner           = { name -> "الفائز: $name 🎉" },
    pvpDraw             = "تعادل!",
    pvpSurrenderConfirm = { name -> "$name، هل أنت متأكد أنك تريد الاستسلام؟\nسيُعلن خصمك فائزاً." },

    shopTitle       = "متجر الحزم",
    shopPackNameFor = { pair -> if (pair == "he-ru") "حزمة عبرية" else "حزمة إنجليزية" },
    shopPackCards   = "5 بطاقات لكل حزمة",
    shopOpenButton  = "فتح",
    shopOpenMultiple= { n -> "فتح ($n حزم)" },
    shopNoPacks     = "لا توجد حزم",
    shopEarnPacks   = "العب PvE أو PvP للحصول على حزمة مجانية",
    shopCountLabel  = "الكمية",
    shopHavePacks   = { n -> "متاح: $n" },

    packOpeningLoading  = "جارٍ فتح الحزمة...",
    packOpeningTitle    = "✦  فتح الحزمة  ✦",
    packOpeningProgress = { rev, total -> "$rev/$total مكشوف" },
    packOpeningRevealAll= "الكشف عن الكل",
    packOpeningToShop   = "إلى المتجر",
    packOpeningToHome   = "الرئيسية",

    newCardsTitle    = "🎴 بطاقات جديدة!",
    newCardsSubtitle = "تمّ تعلّم الكلمات — تمّ الحصول على البطاقات!",
    newCardsCollect  = "استلام الكل",

    statsPlayerTitle     = "إحصائيات اللاعب",
    statsProgressSection = "التقدّم",
    statsWordsLearned    = "الكلمات المُتعلَّمة",
    statsAccuracy        = "دقة الإجابات",
    statsSeriesSection   = "السلسلة",
    statsCurrentStreakLabel = "الحالية",
    statsRecordLabel     = "الرقم القياسي",
    statsStreakDays       = { n -> "$n أيام" },
    statsPvpSection      = "وضع PvP",
    statsPvpWins         = "انتصارات",
    statsPvpLosses       = "خسائر",
    statsPvpDraws        = "تعادلات",
    statsBestPvpScore    = "أفضل نتيجة",

    wordStatsTitle          = "إحصائيات الكلمات",
    wordStatsSortDifficult  = "الأصعب",
    wordStatsSortEasiest    = "الأسهل",
    wordStatsSortFrequent   = "الأكثر تكرارًا",
    wordStatsSortRecent     = "الأحدث",
    wordStatsEmpty          = "لا توجد بيانات بعد.\nابدأ التعلّم!",
    wordStatsProblemTitle   = { n -> "كلمات صعبة: $n" },
    wordStatsProblemSubtitle= "اضغط لبدء مراجعة الأخطاء",
    wordStatsErrors         = { pct -> "أخطاء $pct%" },
    wordStatsEncounters     = { n -> "$n مرات" },

    achievementsTitle    = "الإنجازات",
    achievementsProgress = { got, total -> "تمّ الحصول على: $got / $total" },
    achievementsRemaining= { n -> "متبقّي $n" },
    achievementsAllDone  = "تمّ الحصول على الكل! 🎉",
    achievementsReward   = "🏆 المكافأة",

    settingsTitle                  = "الإعدادات",
    settingsProfileSection         = "الملف الشخصي",
    settingsAvatarLabel            = "الصورة الرمزية",
    settingsFromGallery            = "من المعرض",
    settingsPlayerName             = "اسم اللاعب",
    settingsCancelButton           = "إلغاء",
    settingsAppearanceSection      = "المظهر",
    settingsDarkTheme              = "الوضع الداكن",
    settingsLanguageSection        = "اللغات",
    settingsTasksSection           = "التمارين",
    settingsStudyLanguage          = "لغة التعلّم",
    settingsDefinitionMode         = "اختبار التعريف",
    settingsFillBlankMode          = "اختبار الملء",
    settingsQuizTypesLabel         = "أنواع الاختبارات (PvE)",
    settingsQuizTypesCount         = { n, total -> "$n من $total" },
    settingsDone                   = "تمّ",
    settingsProblemWordsSource     = "احتساب الكلمات الصعبة من",
    settingsProblemWordsSourceTitle= "احتساب الأخطاء من",
    settingsNativeLanguage         = "اللغة الأم",
    settingsChooseNativeLanguage   = "اختر اللغة الأم",
    settingsStudyLanguageTitle     = "لغة التعلّم",
    settingsProgressSection        = "التقدّم",
    settingsPlayerStats            = "📊  إحصائيات اللاعب",
    settingsWordStats              = "📖  إحصائيات الكلمات",
    settingsAchievements           = "🏆  الإنجازات",

    quizModeLabels = linkedMapOf(
        "foreign" to "بلغة التعلّم",
        "native"  to "باللغة الأم",
        "both"    to "كلا الخيارين",
    ),
    quizTypeLabels = linkedMapOf(
        "translation" to "ترجمة (4 خيارات)",
        "definition"  to "تعريف",
        "fill_blank"  to "ملء الفراغ",
    ),
    problemWordsSourceLabels = linkedMapOf(
        "both"     to "PvE + PvP معًا",
        "pve_only" to "PvE فقط",
        "pvp_only" to "PvP فقط",
    ),
)

fun appStringsFor(langCode: String): AppStrings = when (langCode) {
    "ru" -> RuStrings
    "en" -> EnStrings
    "de" -> DeStrings
    "fr" -> FrStrings
    "es" -> EsStrings
    "zh" -> ZhStrings
    "ja" -> JaStrings
    "ar" -> ArStrings
    else -> RuStrings
}
